x=["123","456"]
print(f" x ={x}, length of x ={len(x)}, type of x ={type(x)}")
print("-"*135)
x.append("789") 
print(f" x after append('789') ={x}, length of x ={len(x)}, type of x ={type(x)}")
print("-"*135)
y=x
print(f" after y=x ={y}, length of y ={len(y)}, type of y ={type(y)}")
print("-"*135)
y.clear()
print(f" y after clear() on y ={y}, length of y ={len(y)}, type of y ={type(y)}")
print(f" x after clear() on y ={x}, length of x ={len(x)}, type of x ={type(x)}")
print("-"*135)
y=x.copy()
print(f" y after x copy() ={y}, length of y ={len(y)}, type of y ={type(y)}")
print("-"*135)
print("as now the value of y and x is cleared we will re assign values")
print()
x=["my","name","is","shantanu"]
print(f" x ={x}, length of x ={len(x)}, type of x ={type(x)}")
print("-"*135)
print()
y=x.copy()
print(f" y after x copy() ={y}, length of y ={len(y)}, type of y ={type(y)}")
print("-"*135)
y.clear()
print(f" y after clear() on y ={y}, length of y ={len(y)}, type of y ={type(y)}")
print(f" x after clear() on y ={x}, length of x ={len(x)}, type of x ={type(x)}")
y.append(["hell","yeah !"])
print(f" y after append(['hell','yeah !']) ={y}, length of y ={len(y)}, type of y ={type(y)}")
y.clear()
print(f" y after clear() on y ={y}, length of y ={len(y)}, type of y ={type(y)}")
y.extend(["hell","yeah !"])
print(f" y after extend(['hell','yeah !']) ={y}, length of y ={len(y)}, type of y ={type(y)}")

